n1=input("What is your name in this adventure?")

print("Welcome to the game",n1)
choice1=int(input("What adventure will you pick 1 or 2?"))
while (choice1==1):
  print("You choose adventure one")
  print('Hello',n1,'welcome to your new mission.The new mission consist,if you decide to accept it,is to come back to the past and stop the terrorist Amira Zadin,before she throws a nuclear bomb')
  
  q1=input("Will you accept it(yes/no)?") 
  if (q1=='yes'):
    print("Lets continue 🤟")
    print("Lets move to Paris,that we will meet with Chris,your new partner")
    print('Hours later...')
    print('Chris:Hi my name is Chris nice to meet you')
    print('You:Thanks you too')
    print('You:😊😀')
    print('You:So were are we going next???')
    print('Chris:We are going to the Louvre to stole a code that is in a painting')
    print('Chris:Lets move')
    print('MINUTES LATER...')
    print('Chris:We are here')
    qu1=input('Chris:Will you join me?(yes/no)')
    if (qu1=='yes'):
      print('Chris:So lets goooo😃')
      print('Chris:We are here')
      que1=input('Chris:Will you help me steal it?(yes/no)')
      if (que1==que1):
        print('Chris:Ok,so come on')
        print('Chris:Lets move')
        print('Later...')
        print('Chris:We finished🥳🥳🤩')
      print('Chris:We have finish here')
      print('Chris:Lets go to the hotel')
      que1=input('Chris:Will you go the hotel with me? (yes/no)')
      if (que1=='yes'):
        print('In the hotel...')
      print('Chris: Okay',n1,'we need to give this code to Dr.Wild, so he can finish the time machine')
      ques1=input('Chris: Would you like to join me? (yes/no)')
      if (ques1=='yes'):
        print('Chris:Good you decide to go with me')
        print('Chris:I think I will need help')
        print('Chris:Im going to call some contacts, stay here')
        print('Minutes later....')
        print('Chris:We are waiting for two partners, their names are Zara and Neph')
        print('MINUTES LATER...')
        print('Zara and Neph arrive...')
        print('You:Hi,my name is ',n1)
        print('Zara:Nice to meet you😀')
        print('Neph:Its a pleasure')
        print('Neph and you shake hands')
        print('Chris:Well...')
        print('Chris:Now that we all know each other...')
        print('Chris:We need to get back to the hotel🏨')
      else:
        print('Chris:Ok so you need to stay here,in the hotel')
        print('Chris:Its not safe out there')
        print('Chris:😬')
        print('You:🫡')
      print('So now that we are here in the hotel')
      print('Chris:Lets eat')
      print('Zara:Yessss,Im so hungryyy')
      print('Neph:Im starvingggg😫')
      quest1=input('Chris:Would you like to eat with us?(yes/no)🤗🥞')
      if (quest1=='yes'):
        print('Chris:Ok so lets go to the hotel restaurant🥘🍜')
        print('YOU DO WITH THEM TO THE HOTEL RESTAURANT🌮🍟')
        print('Waiter:What would you like to order?')
        print('Chris:I want tacos what do you say guys?')
        print('Zara: Yes! we can all share an order ')
        print('Neph:Yes, and maybe some sodas')
      print('Zara:What do you think',n1,'?')
      print('You:Yes!!🌮')
      print('Neph calls the waiter🤵🏻')
      print('Waiter:Yes?')
      print('Waiter:What will you order?')
      print('Neph:We would like some tacos')
      print('Waiter:How many tacos will you want?')
      print('Chris:I think ten tacos will be ok')
      print('You:Thanks')
      print('Waiter leaves...')
      print('MINUTES LATER...')
      print('Waiter:The tacos are ready')
      print('The waiter put the tacos at the table')
      print('You start to eat with them')
      print('You are finished')
      print('They finish✅ ')
      print('Chris:The agency pays so lets go to our rooms to rest')
      print('Zara:Ok,goodbye👋')
      print('Neph:Yessss!!! Im so tired 😴🥱 ')
      print('You:Goodbye,good night 🌌')
      print('NEXT DAY...🌞🌞🌞')
      print('You get ready')
      print('You go to have your breakfast at the hotel restaurant')
      print('While you are eating 📱')
      print('The phone rings📱📱')
      print('You see...')
      print('Incoming Call from Chris')
      print('You answer')
      print('Chris:Sooo we need to investigate more about Amira so we will travel to the past')
      print('Chris:Its very dangerous...')
      questi1=input('Will you come with us?(yes/no)')
      if (questi1=='yes'):
        print('Chris:We will have a meeting in Zaras room')
        print('Chris:We need for you to be there')
        print('Chris:The agency will communicate us the plan through a message that will destroy itself in 4 minutes after the message is repeated')
        print('Chris:So lets hurry up')
        print('We need to begin with the missionas soon as possible!!!')
        print('YOU AND CHRIS ARE WALKING TO ZARAS ROOM🏃🏻‍♀️🏃🏻‍♀️')
        print('YOU ARE IN THE DOOR JUST ABOUT TO KNOCK...')     
        print('WHEN SUDDENLY ZARA AND NEPH THEY SCARE YOU')
        print('You all laughed🤣🤣 and enter the room')
        print('Zara:Ok so Neph and I went for the message')
        print('Neph:Here is the message...✉️')
        print('Message:You need to go to New York go to the top of the Liberty Statue 🗽,then press the botton infornt of you and that will get you to were you need to go in time...')
        print('Message:Will you want yo repeat it?')
        print('Chris:No')
        print('Message:Ok so the message will self-destruct,its recommendable to through it away...')
        print('Message:A countdown will start:')
        print('Chris:Lets through it away...')
        print('Message:5,4,3,2,1...')
        print('POWWWW💥💥')
        print('Zara:Thank god we throw it away')
        print('Neph:Yesss that was close')
        print('You:Ufff yess')
        print('Neph:So lets pack and go to New York')
        print('Zara:Im buying the plane tickets 🎟')
        print('Zara:Our plane takes off at 9:00am tomorrow ')
        print('You:Ok so lets go to our rooms to pack')
        print('You:We will see each other at the hotel restaurant at 8:00pm to have dinner')
        print('YOU PACK,REST A LITTLE AND IN THAT TIME...')
        print('TIME PASES FLYING...')
        print('NOW ITS 8:00pm')
        print('You get ready to go to dinner 🥘')
        print('YOU GET DOWN IN THE ELEVATOR ')
        print('THEN YOU SEE CHRIS,NEPH AND ZARA there waiting...')
        print('Chris:Ok so lets take a taxi and then go')
        print('You:Ok')
        print('YOU ALL SIT IN THE TAXI')
        print('MINUTES LATER...')
        print('You are at the airport')
        questio1=input('Chris:Anyone wants to go to the bathroom?(yes/no)')
        if (questio1=='yes'):
          print('Zara:I do want to go')
          print('Chris:ok so we will wait for you guys here')
        elif (questio1=='no'):
          print('Zara:I do want to go')
          print('Chris:Ok so we will what for you here')
        print('Chris:Now that we are all here...')
        print('Zara:lets continue...🤙')
      print('Lets board the plane✈️ ')
      print('Stewardess:Everyone lets take your seats')
      print('HOURS LATER...')
      print('Captain:Everybody we have arrive to our destination...')
      print('Captain:New York!!!')
      print('You all come down from the airplane and you gathered')
      print('Zara:Well now we need to go to the hotel to leave our stuff')
      print('Two hours later ')
      print('Chris:we will go to the statue of liberty')        
      print('MINUTES LATER...')
      print('Taxi driver:we are here👨🏻👨')
      print('Zara:We need to hurry...')
      print('MINUTES LATER WE ARE IN THE TOP OF IT...')
      print('Neph:Lets go',n1,'press the botton')
      print('You press the botton and it sends you to an old poor house...')
      print('')
##SECOND GAMEEEE    
while (choice1==choice1):
  print("You have choose adventure 2")
  print('The adventure consist in finding and protecting the Itzamna gem,then you will ask,but... protect... from who... We have to protect it from the Company H & U, they want to steal it and sell it to the terrorist! ') 
  q2=input("Will you go with us? (yes/no)")
  if (q2=='yes'):
    print('Lets goooo🤙')
    print('Julia:Hi I am Julia,your partner')
    print('Julia:We have to go to the LA airport then arrive to Mexico city airport🛩,then we will have to...')
    print("BANG BANG BANG 🔫")
    print('You:Runnnnn they are shooting')
    print('POW BANG POW 💣💥')
    print('Julia:That was close, ufff')
    qu2=input("Julia:Dont you think? (yes/no) ?")
  if (qu2=='yes'):
      print("You:Are you hurt?")
      print('Julia:No')
      print('Julia:You?')
    que2=input("yes/no")
    if (que2=='yes'):
      print('Julia:Lets go to the hospital!!🚨🚑')
      print('Doctor:You got shot,but do not worrie I will fix you')
      print('Julia:He is one of the co-wokers from this mission')
      print('Julia:He wont tell anybody')
      print('Doctor:Thats right')
      print('Few days later...')
      print('Doctor:You are fine,you can continue your mission😀')
    else:
      print('Julia:Few,thank god')
      print('Julia:Sooo lets continue')
    print('Julia:Now we will have to take a taxi to go to the hotel,then at 8:00am we will take another flight to Cancun')
    print('Next day...')
    print('👀Looking for Julia')
    print('You see her in the hallway of the hotel')
    print('Ha,she is talking to someone')
    print('You think that is suspicious🧐')
    print('You go out of the room')
    print('She sees you...')
    print('And she does this🤫...')
    print('You sneek out of the hallway')
    print('You are in your room know')
    print('Julia cames in...')
    print('Julia:He was the suspicious one')
    print('Julia:That was one of the member of the Company H & U')
    print('Julia:I am infiltrated')
    print('You:Ok')
    print('Julia: Im going to an event to get information about the gem and the Company')
    qu2=input('Julia: Do you want to come with me? (yes/no)')
    if (qu2=='yes'):
      print('Julia:Ok come with me')
      print('You follow her')
      print('Julia:Ok so,we are going to a Gala so we need to dress up')
      print('The Gala will be in a mansion')
      print('One hour later...')
      print('Julia and you get out')
      print('Julia:You look good, lets go🤩🤙')
      print('You arrive to the gala...')
      print('Everything seems fine😃 but...')
      print('Julia:There they are the partners form the Company H & U')
      print('Julia:Look at your left')
      print('👁 👁')
      print(' 👄')
      print('You look at you left')
      print('See some mysterious guys')
      print('Julia:Lets go talk to them')
      que2=input('Julia:Will you come with me? (yes/no)')
      if (que2=='yes'):
        print('Hello,how are you tonight ladies and gentleman')
        print('Nft:Fine,and you Mis..')
        print('Julia:Miss Jones')
        print('They ask you your name and lastname')
        ques2=input('What will be your last name?')
        print('My name is:',n1,ques2)
        print('Julia:So lets continue')
        print('Nft:So why are you here?')
        print('Julia:I workwith the company so I was invited with my friend,they said I could bring a person')
        print('Nft:Aaa ok')
        print('Julia:Mister Chang what is your next goal?')
        print('Mister Chang:Well our next goal is the Itzamna gem')
        print('Mister Chang:Wait I dont remember you from anywhere,are you new?')
        print('Julia:Yes,I have been in the Company for just one week so I am trying to know the goals of this Company')
        print('Mister Chang:Very well,you are a young lady who like to be prepared')
        print('Julia:Yes I am')
        print('Julia:Thanks Mister Chang')
        print('Mister Chang:Enjoy the party')
        print('Julia:You too')
        print('You whisper to Julia')
        print('You:Do you know this man?')
        print('Julia:Yes,he is the head of the Company')
        print('You see that Julia is talking with Mr.Chang far away from the party')
        print('You:OMG 🤔')
        print('THE PARTY ENDS...')
        print('Julia:Well we are done here lets go to the hotel')
        print('Julia calls a taxi')
        print('YOU GO IN,MINUTES LATER YOU ARE IN THE HOTEL...')
        print('Julia:lets go to your room is closer')
        print('Julia:Need to tell you what in found')
        print('Julia:They will try to sell it to terrorist we need to hack their computers and then download all their information')
        questi2=input('Julia:Do you know how to hack?(yes/no)')
        if (questi2=='yes'):
          print('Julia:Help me hack this')
          print('Julia:I will start with the files and you will start with the passwords')
          questio2=int(input('Enter password: '))
          ##This will be a password code
        print('Password 4 number')
        while True:
          inport
        comparador=8974
        if (questio2!=8974):
          print('Enter password again')
          print('Ill give you a hint, it doesnt have the numbers 1,2,3,5 and 6, GOOD LUCK 🍀')
        else:
          print('Correct password')
          print('You did it!')
          ##The player is going to be trying over and over again
          print('Julia:Ok so can you order food I am still a little hungry')
          print('You: I will')
          print('You order the food')
      else:
        print('Julia:Ok so please stay at your hotel room')
        print('You:Ok')
        quest2=input('Are you hungry?(yes/no)')
        
        if (quest2=='yes'):
          print('Calling 001...')
          print('Means ROOM SERVICE')
          print('Person:Hotel... what do you need?')
          print('You:I am calling for room service, for food')
          questi2=input('Person:What food would you like to order?')
          print('You:I would like to order ',questi2)
          print('Person:sure,your ',n1,' will be in a moment')
          print('MOMENTS LATER...')
          print('KNOCK KNOCK✊')
          print('Person:Hi 👋did you order food?')
          print('You:Yes,hi,thanks for the food')
          print('You:Byeeee👋👋👋')
          print('You finish eating...')
          print('JULIA COMES BACK')
          print('Julia knocks the door')
          print('You let her in')
          print('You:Hi Julia')
          print('You:What is the information that you have?')
          print('Julia: I saw that the terrorist is here, in the hotel! ')
          print('Julia: The company and the terrorist are going to a house outside the city to make the exchange')
          print('Julia: The only thing is that I dont know where is this house located')
          
          questi2=input('Julia: Can you help me find it?(Yes/No)')
          if(questi2=='No'):
            print('Julia:This is the plan')
            print('Julia:First activate your location in you phone📱')
            print('You activate it')
            print('Julia:Then lets hack the parteners from the Company')
            print('Julia:Then we will follow them to the house')
            print('Julia:And then wait for them')
            print('Julia:You will infiltrate as a bartender')
            print('Julia:We will need a headphone for me to hear the conversation ')
            print('Julia:Ok so when I talk you will hear me through the headphones')
            print('Julia:Lets try it')
            questio2=input('Julia:Do you hear me?(yes/no)')
            if (questio2=='yes'):
              print('Julia:Ok')
              print('Julia:Everything is ready')
            else:
              print('Julia:Ohhh nooo')
              print('The headphoneee')
              print('Julia:We will need to fix it')
              print('We will need to go back to the hotel')
              question2=input('Julia:Are you coming?(yes/no)')
              if (question2=='yes'):
                print('Julia:Ok')
                print('Julia:Lets move')
                print('Julia:Come on')
                print('MOMENTS LATER...')
                print('Julia:We are here')
                print('Julia:We need to hurry')
                print('MOMENTS LATER...')
                print('Julia:')
                print('YOU AND JULIA ARRIVE TO THE ROOM')
                print('THEN YOU AND JULIA FIX THE HEADPHONE')
                print('Julia:We finish fixing it')
                print('Lets go to the house')
              print('Julia:I already found the house')
              print('Julia: Do you hear me now?')
              print('You: Yes I can hear you 😗')
              print('Julia:okay, you are the bandtender and you have to prepare some drinks for them')
              print('Julia:There is in your pocket a bottle with a liquid that will make them tell the whole truth, record them')
              print('THE TERRORIST AND MISTER CHANG START TO TELL ALL THEIR TRUTHS 😵')
              print('Julia:Good, they are talking, lets move on')
              print('Julia:Im going to approach them carefully and throw a gas at them that will make them sleep, run away as soon as possible!')
              print('YOU RUN 🏃💨💨')
              print('Julia: in the car is a gas mask that you can use, put it on and come with me ')
              print('YOU PUT ON THE MASK 🤿')
              print('Julia:The bodyguards are here, I need your help, COME QUICKLY!!')
              print('YOU ENTER TO THE HOUSE')
              print('Julia: There is four bodyguards, Ill take care of these two, you take care of the others ok? (yes/no) ')
              print('Julia: Good, lets kick some faces 🥊')
              question1n2=input('Julia: Im ready, you need help? (yes/no)')
              if (question1n2=='yes'):
                print('Julia: Fine, you are good at fighting 🙃😱')
              print('You:Thanks...')
              print('Julia:Look!, there is a case, maybe the gem is there!!!🤩')
              print('YOU OPEN THE CASE 💎')
              print('Julia:LOOK, there is a note')
              print('Bring the money to the place where we met, there is the gemstone')
              print('Julia: This must be a joke, how are we going to know where they met, do you know anything',n1,'?')
              print('Julia:wait, I know how') 
              question1nn2=input('Julia:You record them right? (yes/no)')
              if (question1nn2=='yes'):
                print('Julia: Great, lets go back to the hotel and see of they said where they met')
              else:
                print('Julia:Ok, lets ho back to the hotel and talk to others to see if they know anything about Mr.Chang and the terrorist')
print(''HOURS LATER ⏱)

print('Okay',n1,'Look, there is my other partner follow me')
print('YOU FOLLOW HER 🏃🏻‍♀️')
              